"""add is_online to schedule_items and change_requests

Revision ID: 2f166d445031
Revises: 82ca6bc93b96
Create Date: 2026-10-09 18:40:56.984570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f166d445031'
down_revision: Union[str, Sequence[str], None] = '82ca6bc93b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_requests', sa.Column('is_online', sa.Boolean(), nullable=True))
    op.add_column('schedule_items', sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_items', 'is_online')
    op.drop_column('change_requests', 'is_online')
    # ### end Alembic commands ###
