"""add_is_cbt_exam

Revision ID: 5511b67f3035
Revises: i9d0e1f2g3h4
Create Date: 2026-07-07 02:56:11.793630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5511b67f3035'
down_revision: Union[str, Sequence[str], None] = 'i9d0e1f2g3h4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_cbt_exam', sa.Boolean(), server_default='false', nullable=False))
    op.execute("""
        UPDATE courses
        SET is_cbt_exam = TRUE
        WHERE id IN (
            SELECT DISTINCT s.course_id
            FROM schedule_items s
            CROSS JOIN unnest(s.room_ids) as r_id
            WHERE r_id IN (
                SELECT id FROM rooms WHERE UPPER(name) LIKE '%CBT%'
            )
        );
    """)
    op.execute("UPDATE courses SET title = '' WHERE title IS NULL;")
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('courses', 'is_cbt_exam')
    # ### end Alembic commands ###
