"""Fix Room unique constraint

Revision ID: e84b138e0567
Revises: fa8474ebeb56
Create Date: 2026-05-20 19:35:50.936220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84b138e0567'
down_revision: Union[str, Sequence[str], None] = 'fa8474ebeb56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=False)
    op.create_unique_constraint('uq_room_name_faculty', 'rooms', ['name', 'faculty_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_name_faculty', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    # ### end Alembic commands ###
